create table Exemplaire (reference varchar(255) not null, etat integer, primary key (reference))
create table Exemplaire (reference varchar(255) not null, etat integer, primary key (reference))
create table Exemplaire (reference varchar(255) not null, etat integer, primary key (reference))
create table Exemplaire (reference varchar(255) not null, etat integer, primary key (reference))
create table Exemplaire (reference varchar(255) not null, etat varchar(255), primary key (reference))
create table Exemplaire (reference varchar(255) not null, etat varchar(255), primary key (reference))
create table Exemplaire (reference varchar(255) not null, etat varchar(255), media_id bigint, primary key (reference))
create table t_medias (Type varchar(1) not null, id bigint not null auto_increment, datePublication datetime, name varchar(255), primary key (id))
alter table Exemplaire add constraint FK2lbdc4d9ureiwqws6ctobxbtg foreign key (media_id) references t_medias (id)
create table Exemplaire (reference varchar(255) not null, etat varchar(255), media_id bigint, primary key (reference))
create table t_medias (Type varchar(1) not null, id bigint not null auto_increment, datePublication datetime, name varchar(255), primary key (id))
alter table Exemplaire add constraint FK2lbdc4d9ureiwqws6ctobxbtg foreign key (media_id) references t_medias (id)
create table Exemplaire (reference varchar(255) not null, etat varchar(255), media_id bigint, primary key (reference))
create table t_medias (Type varchar(1) not null, id bigint not null auto_increment, datePublication datetime, name varchar(255), primary key (id))
alter table Exemplaire add constraint FK2lbdc4d9ureiwqws6ctobxbtg foreign key (media_id) references t_medias (id)
create table Exemplaire (reference varchar(255) not null, etat varchar(255), media_id bigint, primary key (reference))
create table t_medias (Type varchar(1) not null, id bigint not null auto_increment, datePublication datetime, name varchar(255), primary key (id))
alter table Exemplaire add constraint FK2lbdc4d9ureiwqws6ctobxbtg foreign key (media_id) references t_medias (id)
create table Exemplaire (reference varchar(255) not null, etat varchar(255), media_id bigint, primary key (reference))
create table t_medias (Type varchar(1) not null, id bigint not null auto_increment, datePublication datetime, name varchar(255), primary key (id))
alter table Exemplaire add constraint FK2lbdc4d9ureiwqws6ctobxbtg foreign key (media_id) references t_medias (id)
create table Exemplaire (reference varchar(255) not null, etat varchar(255), media_id bigint, primary key (reference))
create table t_medias (Type varchar(1) not null, id bigint not null auto_increment, datePublication datetime, name varchar(255), primary key (id))
alter table Exemplaire add constraint FK2lbdc4d9ureiwqws6ctobxbtg foreign key (media_id) references t_medias (id)
create table Exemplaire (reference varchar(255) not null, etat varchar(255), media_id bigint, primary key (reference))
create table t_medias (Type varchar(1) not null, id bigint not null auto_increment, datePublication datetime, name varchar(255), primary key (id))
alter table Exemplaire add constraint FK2lbdc4d9ureiwqws6ctobxbtg foreign key (media_id) references t_medias (id)
create table Exemplaire (reference varchar(255) not null, etat varchar(255), media_id bigint, primary key (reference))
create table t_medias (Type varchar(1) not null, id bigint not null auto_increment, datePublication datetime, name varchar(255), primary key (id))
alter table Exemplaire add constraint FK2lbdc4d9ureiwqws6ctobxbtg foreign key (media_id) references t_medias (id)
create table Exemplaire (reference varchar(255) not null, etat varchar(255), media_id bigint, primary key (reference))
create table t_medias (Type varchar(1) not null, id bigint not null auto_increment, datePublication datetime, name varchar(255), primary key (id))
alter table Exemplaire add constraint FK2lbdc4d9ureiwqws6ctobxbtg foreign key (media_id) references t_medias (id)
create table Exemplaire (reference varchar(255) not null, etat varchar(255), media_id bigint, primary key (reference))
create table t_medias (Type varchar(1) not null, id bigint not null auto_increment, datePublication datetime, name varchar(255), primary key (id))
alter table Exemplaire add constraint FK2lbdc4d9ureiwqws6ctobxbtg foreign key (media_id) references t_medias (id)
create table Exemplaire (reference varchar(255) not null, etat varchar(255), media_id bigint, primary key (reference))
create table t_medias (Type varchar(1) not null, id bigint not null auto_increment, datePublication datetime, name varchar(255), primary key (id))
alter table Exemplaire add constraint FK2lbdc4d9ureiwqws6ctobxbtg foreign key (media_id) references t_medias (id)
create table Exemplaire (reference varchar(255) not null, etat varchar(255), media_id bigint, primary key (reference))
create table t_medias (Type varchar(1) not null, id bigint not null auto_increment, datePublication datetime, name varchar(255), primary key (id))
alter table Exemplaire add constraint FK2lbdc4d9ureiwqws6ctobxbtg foreign key (media_id) references t_medias (id)
create table Exemplaire (reference varchar(255) not null, etat varchar(255), media_id bigint, primary key (reference))
create table t_medias (Type varchar(1) not null, id bigint not null auto_increment, datePublication datetime, name varchar(255), primary key (id))
alter table Exemplaire add constraint FK2lbdc4d9ureiwqws6ctobxbtg foreign key (media_id) references t_medias (id)
create table Exemplaire (reference varchar(255) not null, etat varchar(255), media_id bigint, primary key (reference))
create table t_medias (Type varchar(1) not null, id bigint not null auto_increment, datePublication datetime, name varchar(255), primary key (id))
alter table Exemplaire add constraint FK2lbdc4d9ureiwqws6ctobxbtg foreign key (media_id) references t_medias (id)
create table Exemplaire (reference varchar(255) not null, etat varchar(255), media_id bigint, primary key (reference))
create table t_medias (Type varchar(1) not null, id bigint not null auto_increment, datePublication datetime, name varchar(255), primary key (id))
alter table Exemplaire add constraint FK2lbdc4d9ureiwqws6ctobxbtg foreign key (media_id) references t_medias (id)
create table Exemplaire (reference varchar(255) not null, etat varchar(255), media_id bigint, primary key (reference))
create table t_medias (Type varchar(1) not null, id bigint not null auto_increment, datePublication datetime, name varchar(255), primary key (id))
alter table Exemplaire add constraint FK2lbdc4d9ureiwqws6ctobxbtg foreign key (media_id) references t_medias (id)
